kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-storage-class
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: gp2 
  zones: us-west-2a
  iopsPerGB: "10" 
  fsType: ext4
