apiVersion: v1
kind: Namespace
metadata: 
  name: hhs-dev-02
spec: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: screening-dev-02
  namespace: flux-system
spec:
  interval: 1m
  chart: 
    spec:
      chart: screening
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-3rd
  targetNamespace: hhs-dev-02
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: applications-dev-02
  namespace: flux-system
spec:
  interval: 1m
  chart: 
    spec:
      chart: applications
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-dyp
  targetNamespace: hhs-dev-02
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notify-dev-02
  namespace: flux-system
spec:
  interval: 1m
  chart: 
    spec:
      chart: notify
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-csdn
  targetNamespace: hhs-dev-02
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cockatoo-dev-02
  namespace: flux-system
spec:
  interval: 1m
  chart: 
    spec:
      chart: cockatoo
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-zoo
  targetNamespace: hhs-dev-02
---
