apiVersion: v1
kind: Namespace
metadata: 
  name: hhs-dev-01
spec: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: screening
  namespace: flux-system
spec:
  interval: 1m
  chart: 
    spec:
      chart: screening
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-3rd
  targetNamespace: hhs-dev-01
