apiVersion: v1
kind: Namespace
metadata: 
  name: hhs-dev-01
spec: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-ha
  namespace: flux-system
spec:
  interval: 1m
  chart: 
    spec:
      chart: rabbitmq-ha
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-3rd
  targetNamespace: hhs-dev-01
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: applications-dev-01
  namespace: flux-system
spec:
  interval: 1m
  chart: 
    spec:
      chart: applications
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-dyp
  targetNamespace: hhs-dev-01
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: activemq-dev-01
  namespace: flux-system
spec:
  interval: 1m
  chart: 
    spec:
      chart: activemq
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-csdn
  targetNamespace: hhs-dev-01
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cockatoo-dev-01
  namespace: flux-system
spec:
  interval: 1m
  chart: 
    spec:
      chart: cockatoo
      version: '1.0.0'
      sourceRef:
        kind: HelmRepository
        name: chartmuseum-zoo
  targetNamespace: hhs-dev-01
---
