apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-persistent-volume-claim
  namespace: hhs-dev-01
spec:
  storageClassName: aws-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  10Gi